apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit-deployment
  labels:
    app: ratelimit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
    spec:
      containers:
      - name: ratelimit
        image: hxy9243/example_ratelimit:0.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: mymaster
        - name: REDIS_SENTINEL_ADDR
          value: redis.ratelimit.svc.cluster.local:26379
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimited-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: ratelimit
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
